version: '3.7'
services:
  api:
    image: chinwewenchas/urlshortener:v1
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '9991:9991'
    environment:
      NODE_ENV: production
      LOG_LEVEL: error
      SERVER_PORT: 8080
    volumes:
      - ./logs/:/opt/app/logs/
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M

  prometheus:
    image: prom/prometheus:v2.19.1
    ports:
      - '9090:9090/tcp'
    volumes:
      - prometheus-data:/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.0.3
    ports:
      - '3000:3000/tcp'
    volumes:
      - grafana-data:/var/lib/grafana
  
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'

volumes:
  prometheus-data:
  grafana-data: